### ISSUE TITLE
Multi-smelter stalls when input is full

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#417] opened 2019-02-11 06:46 UTC
stack size is unimportant, so long as the prior operation has completed and something remains in every input slot the smeltery just enters an idle state that doesn't change.

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Multi-smelter stalls when input is full" "stack size is unimportant, so long as the prior operation has completed and something remains in every input slot the smeltery just enters an idle state that doesn't change."`
Attachments:

**Comment by Saereth** [comment] 2019-02-11 13:22
I cannot reproduce this, full buffer is smelting fine for me

**Comment by Saereth** [comment] 2019-02-11 13:24
can you post a screen shot of your setup showing the power as well as the machine ui and input/output slots please

**Comment by Saereth** [comment] 2019-02-12 21:41
Vyraal has an issue open with gtce now, closing this as a duplicate

**Closed by Saereth** 2019-02-12 21:41 UTC
Labels: help wanted
