### ISSUE TITLE
Quartzes arent smeltable making slivers and vis resonators not craftable before lv

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#562] opened 2019-03-05 00:36 UTC
Submitter: `coolprez#8206`
Body: `OwO issue "Quartzes arent smeltable making slivers and vis resonators not craftable before lv"`
Attachments:

**Comment by Vyraal1** [comment] 2019-03-05 01:18
this should be fixed already, duplicate of https://github.com/Vyraal1/FTB-Interactions/issues/521

**Comment by Vyraal1** [comment] 2019-03-06 02:18
Actually another issue came up with this, you need to autoclave chipped quartz to get the slivers, was there another way to get slivers? @Saereth

**Comment by Saereth** [comment] 2019-03-06 07:09
there is an alternate route already in place you shape craft flawed quartzite/quartz/certus into 2 chipped and then you starlight altar transform them to slivers, its the way to make them pre-autoclave and there is a quest for it already in the magic stick questline

**Closed** 2019-03-08 18:23 UTC
Labels: Fixed next update
