### ISSUE TITLE
repeated disconnecting because of bad potion packet

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#693] opened 2019-03-22 22:43 UTC
Submitter: `coolprez#8206`
Body: `OwO issue "repeated disconnecting because of bad potion packet"`
Attachments:

**Comment by Saereth** [comment] 2019-03-25 15:08
this has longer happened and cant reproduce, closing for now

**Closed by Saereth** 2019-03-25 15:08 UTC
Labels: bug, help wanted
